Time feature
ruuke/RACK-app pull request #1
Opened 2019-03-18 09:24 UTC by ruuke

2019-03-18 12:37 UTC, BubuntuClu commented on app.rb
> +        @time << Time.now.method(option).call
лучше сделать класс, который будет этим заниматься. парсить параметры и возвращать нужные строки ошибок или переданного времени. сейчас у тебя монолит такой, который все делает. а вдруг тебе понадобиться еще где-то внедрить такую штуку?

2019-03-19 07:02 UTC, BubuntuClu commented on timenow.rb
> +        rescue NameError
идея прикольная, но мне кажется странным такая обработка через `rescue`.
@psylone что скажешь?

2019-03-19 07:02 UTC, BubuntuClu commented on timenow.rb
> +    self.parse
это лучше делать отдельным вызовом. так же как у тебя работает ` Time.now.method(option).call`

2019-03-19 12:55 UTC, psylone commented on timenow.rb
> +        rescue NameError
Я бы задал явно, потому что нет гарантии что в общем случае названия сегментов времени из параметра будут совпадать с названиями методов класса `Time`.

2019-03-19 13:00 UTC, psylone requested changes

2019-03-19 13:00 UTC, psylone commented on timenow.rb
> +        rescue NameError
Но это не так принципиально, как то что класс `TimeNow` на самом деле ничего не должен знать о rack приложении, в частности, о статусе ответа. Идея в том что класс форматтер времени должен принимать на вход строку с форматом и производить вычисления. Также предоставлять API чтобы клиентский код мог понимать удачно ли спарсилась строка и получить результат. Например:

```ruby
time_fmt = TimeFormatter.new(@request.params[:format])
time_fmt.parse!
time_fmt.success?
time_fmt.result
```

2019-03-19 13:00 UTC, psylone commented on app.rb
> +    @time = TimeNow.new(env).parse
Лучше назвать класс `TimeFormatter`.

2019-03-19 13:00 UTC, psylone commented on app.rb
> +    @time = TimeNow.new(env).parse
Логика обработки пути запроса должна быть в этом классе. Также как и формирование rack совместимого ответа, включая установку статуса ответа.

2019-03-19 13:00 UTC, psylone commented on app.rb
> +    @time = TimeNow.new(env).parse
Используй объекты классов `Rack::Request` и `Rack::Response`.

2019-03-20 21:43 UTC, psylone approved these changes

2019-03-20 21:43 UTC, psylone commented on app.rb
> +    rack = Rack::Request.new(env)
Только это `request` )

2019-03-20 21:43 UTC, psylone commented on app.rb
> +    if path != '/time' || rack_params.nil?
Если нет параметра, лучше возвращать 400, поскольку путь был найден.

2019-03-20 21:43 UTC, psylone commented on config.ru
> +require_relative 'time_formatter'
Форматтер лучше зареквайрить там где он непосредственно используется, то есть в `app.rb`.

2019-03-21 05:51 UTC, merged